In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
file_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv'
grid_stab_data = pd.read_csv(file_url)
grid_stab_data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [3]:
X = grid_stab_data.drop(columns=['stab', 'stabf'])
X.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  
1 -1.255012  0.413441  0.862414  0.562139  0.781760  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  
4 -0.554305  0.797110  0.455450  0.656947  0.820923

In [4]:
y = grid_stab_data[['stabf']]
y.head()

stabf
0  unstable
1    stable
2  unstable
3  unstable
4  unstable

In [5]:
y['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train

tau1      tau2      tau3      tau4        p1        p2        p3  \
2694  6.255995  2.542401  7.024714  9.476518  3.529888 -1.224881 -0.688228   
5140  5.070581  5.490253  8.075688  0.761075  4.220888 -1.280596 -1.902185   
2568  1.220072  8.804028  3.874283  8.433949  3.614027 -1.039236 -0.953566   
3671  7.498402  6.697603  8.798626  2.126236  3.134585 -1.581906 -0.589386   
7427  7.074006  1.337511  6.100756  7.759156  2.526922 -0.922540 -0.632600   
...        ...       ...       ...       ...       ...       ...       ...   
2895  9.504984  5.265415  2.029617  8.026334  3.449756 -0.922754 -1.526305   
7813  8.035818  4.632548  1.177810  1.204950  4.093208 -1.568218 -0.819966   
905   7.052560  3.264057  1.405949  4.497549  3.741358 -0.629026 -1.407945   
5192  5.085242  1.790031  2.486392  2.848192  3.159670 -0.892898 -1.025461   
235   1.205354  6.995045  5.930860  2.523856  5.230127 -1.755047 -1.567927   

            p4        g1        g2        g3        g4  
2694 -1.616780  0.568221  0.618403  0.685739  0.660088  
5140 -1.038107  0.443515  0.097244  0.916955  0.129254  
2568 -1.621224  0.908353  0.923594  0.238881  0.660156  
3671 -0.963293  0.260826  0.899003  0.964752  0.600598  
7427 -0.971782  0.984580  0.716082  0.836928  0.165162  
...        ...       ...       ...       ...       ...  
2895 -1.000696  0.191864  0.611297  0.080008  0.350312  
7813 -1.705024  0.223384  0.317770  0.726623  0.441620  
905  -1.704387  0.868306  0.605566  0.100591  0.747320  
5192 -1.241311  0.473917  0.418512  0.326253  0.982488  
235  -1.907153  0.861961  0.202768  0.848373  0.739993  

[8000 rows x 12 columns]

In [7]:
y_train['stabf'].value_counts()

unstable    5092
stable      2908
Name: stabf, dtype: int64

In [8]:
y_test['stabf'].value_counts()

unstable    1288
stable       712
Name: stabf, dtype: int64

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

X_train_scaled

array([[ 0.36732671, -0.98604156,  0.65044706, ...,  0.33985949,
         0.58556788,  0.49223946],
       [-0.06465869,  0.08943734,  1.03507899, ..., -1.5584875 ,
         1.42964862, -1.44352101],
       [-1.46785   ,  1.29841758, -0.50253617, ...,  1.45153362,
        -1.04574277,  0.49248925],
       ...,
       [ 0.65760851, -0.72275633, -1.4058879 , ...,  0.29310048,
        -1.55058661,  0.81034412],
       [-0.05931596, -1.26053241, -1.01047147, ..., -0.38825455,
        -0.72678059,  1.66791568],
       [-1.47321368,  0.63843757,  0.25012249, ..., -1.17410957,
         1.179282  ,  0.78362657]])

In [10]:
y_train

stabf
2694  unstable
5140  unstable
2568  unstable
3671  unstable
7427  unstable
...        ...
2895    stable
7813    stable
905   unstable
5192  unstable
235     stable

[8000 rows x 1 columns]

## Training with Random Forest

In [11]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.metrics import classification_report, confusion_matrix

rnd_clf = RandomForestClassifier(random_state=1)


In [12]:
y_train, y_test = np.ravel(y_train), np.ravel(y_test) # ravel flattens the 2d DataFrame to a 1d array

rnd_clf.fit(X_train_scaled, y_train)
y_pred_rf = rnd_clf.predict(X_test_scaled)


In [13]:
print(classification_report(y_test, y_pred_rf, digits=5))

              precision    recall  f1-score   support

      stable    0.91912   0.87781   0.89799       712
    unstable    0.93409   0.95730   0.94555      1288

    accuracy                        0.92900      2000
   macro avg    0.92660   0.91755   0.92177      2000
weighted avg    0.92876   0.92900   0.92862      2000



In [14]:
confusion_matrix(y_test, y_pred_rf) # order is stable, unstable (sorted alphabetically)

array([[ 625,   87],
       [  55, 1233]], dtype=int64)

## Training with ExtraTreesClassifier

In [15]:
et_clf = ExtraTreesClassifier(random_state=1)

In [16]:
et_clf.fit(X_train_scaled, y_train)
y_pred_et = et_clf.predict(X_test_scaled)

print(classification_report(y_test, y_pred_et, digits=5))

              precision    recall  f1-score   support

      stable    0.94099   0.85112   0.89381       712
    unstable    0.92183   0.97050   0.94554      1288

    accuracy                        0.92800      2000
   macro avg    0.93141   0.91081   0.91967      2000
weighted avg    0.92865   0.92800   0.92712      2000



In [17]:
confusion_matrix(y_test, y_pred_et)

array([[ 606,  106],
       [  38, 1250]], dtype=int64)

## Training with XGBoost

In [18]:
# pip install XGBoost
# You need to install XGBoost

In [19]:
import xgboost

xgb_clf = xgboost.XGBClassifier(random_state=1, max_depth=3, learning_rate=0.1)

xgb_clf.fit(X_train_scaled, y_train)
y_pred_xgb = xgb_clf.predict(X_test_scaled)

print(classification_report(y_test, y_pred_xgb, digits=5))

              precision    recall  f1-score   support

      stable    0.92061   0.84691   0.88222       712
    unstable    0.91896   0.95963   0.93885      1288

    accuracy                        0.91950      2000
   macro avg    0.91978   0.90327   0.91054      2000
weighted avg    0.91955   0.91950   0.91869      2000



In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred_xgb)

0.9195

In [21]:
print(confusion_matrix(y_test, y_pred_xgb))

[[ 603  109]
 [  52 1236]]


In [22]:
print(xgboost.__version__)

1.1.1


## Training with LightGBM

In [23]:
#pip install lightgbm

In [24]:
from lightgbm import LGBMClassifier
lgbm_clf2 = LGBMClassifier(random_state=1)
lgbm_clf2.fit(X_train_scaled, y_train)
y_pred_lgbm2 = lgbm_clf2.predict(X_test_scaled)

print(classification_report(y_test, y_pred_lgbm2, digits=5))

print(confusion_matrix(y_test, y_pred_lgbm2))

print(accuracy_score(y_test, y_pred_lgbm2))

              precision    recall  f1-score   support

      stable    0.92972   0.89185   0.91039       712
    unstable    0.94153   0.96273   0.95202      1288

    accuracy                        0.93750      2000
   macro avg    0.93563   0.92729   0.93120      2000
weighted avg    0.93733   0.93750   0.93720      2000

[[ 635   77]
 [  48 1240]]
0.9375


## Improving Extra Trees Classifier with RandomisedSearchCV

In [25]:
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None]

hyperparameter_grid = {'n_estimators': n_estimators,
                       'min_samples_leaf': min_samples_leaf,
                       'min_samples_split': min_samples_split,
                       'max_features': max_features}


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
rscv_clf = RandomizedSearchCV(ExtraTreesClassifier(random_state=1), hyperparameter_grid, random_state=1, verbose=True)

rscv_clf.fit(X_train_scaled, y_train)
y_pred_rscv = rscv_clf.predict(X_test_scaled)


Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


In [ ]:
print(classification_report(y_test, y_pred_rscv, digits=5))

print(confusion_matrix(y_test, y_pred_rscv))

In [ ]:
#!python -m pip install --upgrade pip

In [ ]:
rscv_clf.best_params_

In [ ]:
# Feature importances
sorted(zip(et_clf.feature_importances_, X.columns), reverse=True)

In [ ]:
et_clf2 = ExtraTreesClassifier(n_estimators=1000, min_samples_split=2,
                               min_samples_leaf=8, max_features=None, random_state=1)
et_clf2.fit(X_train_scaled, y_train)
y_pred_et2 = et_clf2.predict(X_test_scaled)

print(classification_report(y_test, y_pred_et2, digits=5))

In [ ]:
confusion_matrix(y_test, y_pred_et2)